### ISSUE TITLE
Main screen - trips, countries, cities

### ISSUE THREAD

**Issue by kamilslusarczyk** [kamilslusarczyk/local-lingua#6]

**Comment by kamilslusarczyk** [comment]
![main screen](https://user-images.githubusercontent.com/6632929/31578630-5cb93e50-b125-11e7-8baf-775be06789ac.jpg)

**Comment by kasperslusarczyk** [comment]
![main page - logged in](https://user-images.githubusercontent.com/11523252/31584591-81b4f686-b1b1-11e7-8cb6-bcdf4c7d09bd.jpg)
![main page](https://user-images.githubusercontent.com/11523252/31584592-81d3958c-b1b1-11e7-8ae9-e1f4e4e48b07.jpg)
